### ISSUE TITLE
Could use `*` operator overloading for matrix and vector multiplications

### ISSUE THREAD

**Issue by rickbrew** [Sergio0694/ComputeSharp#235] opened 2022-04-25 04:12 UTC
Not sure if bug report or feature request.

While porting this shadertoy, https://www.shadertoy.com/view/tlVGDt, I came across this line of code

```
pos.xy *= rot(.8);
```

`pos` is a `vec3`, aka `float3`
`rot(float)` returns a `mat2`, a 2x2 matrix, aka `float2x2`

So we're multiplying the `XY` portion of a `float3`, which is a `float2`, by a 2x2 float2x2 (matrix)

Except that the `float2 * float2x2` operator does not exist, this does not compile:

```
pos.XY *= rot(0.8f);
```

The line of code that is accepted is:

```
pos.XY = Hlsl.Mul(pos.XY, rot(0.8f));
```

So, can we get `*` hooked up for matrix multiplications? Should it be? Am I translating this GL shader correctly? (I don't know yet, I haven't finished it :)

**Comment by rickbrew** [comment] 2022-04-27 22:39
Also I'm not sure if `*` is a supported way to do this (vector/matrix multiplication) in HLSL shaders, like it is for GLSL (which I see used over on ShaderToy)

If it's not, then it's up to you if you should add this :)

**Comment by Sergio0694** [comment] 2022-04-27 22:42
It's not supported in HLSL, this is a GLSL only feature. We could look into potentially adding it, but not a priority.
Also I'm not entirely sure we should add this in the first place given HLSL specifically doesn't support this syntax 🤔

**Comment by Sergio0694** [comment] 2022-04-27 22:43
Duplicate of #156, closing this one.

**Closed by Sergio0694** 2022-04-27 22:43 UTC
Labels: proposal :bulb:

**Comment by Sergio0694** [comment] 2022-08-28 12:27
Closing this as duplicate, not as completed 😄
