### ISSUE TITLE
Function call produces error 'use of undeclared identifier'

### ISSUE THREAD

**Issue by Iluvatar82** [Sergio0694/ComputeSharp#97] opened 2021-02-21 12:34 UTC
Hi there, I installed Version 1.4.1 via NuGet. I am sorry, if I am doing something wrong here, but I can't find a solution:
```C#
public void Execute(ThreadIds ids)
{
    int offset = ids.X + ids.Y * _size;
    Values[offset] = 0;
}
```
Works as intended and has no Problem, but when I want do do something like:
```C#
private float DummyFunc()
{
    return 0;
}

public void Execute(ThreadIds ids)
{
    int offset = ids.X + ids.Y * _size;
    Values[offset] = DummyFunc();
}
```
I always get the Error:
```The Dxc compiler encountered an error while trying to compile the shader.Make sure to only be using supported features by checking the README file in the ComputeSharp repository: https://github.com/Sergio0694/ComputeSharp.
If you're sure that your C# shader code is valid, please open an issue an include a working repro and the following error message:
hlsl.hlsl:40:21: error: use of undeclared identifier 'DummyFunction'
        Values[i] = DummyFunction();
                    ^
```
It might very well be, that I am just missing something here. Any help would be very appreciated.

**Comment by Sergio0694** [comment] 2021-02-21 14:48
Hi! You didn't do anything wrong, this might very well just be a regression in ComputeSharp v1 😄

I'm no longer maintaining that version, in fact I will eventually just unlist that package from NuGet entirely.
I've been working on a complete rewrite of the library (you can follow the progress in the `dev` branch) for the past few months, and I should be able to finally publish a first preview package for it on NuGet in the coming weeks. I just tried to repro this on ComputeSharp v2 and I can confirm that the code builds and runs just fine there:

```csharp
[AutoConstructor]
internal readonly partial struct MainKernel : IComputeShader
{
    public readonly ReadWriteBuffer<float> buffer;

    private float DummyFunc() => 0;

    public void Execute()
    {
        buffer[ThreadIds.X] = DummyFunc();
    }
}
```

If you'd like to try out a preview package from that version, you can grab it from the CI, by following these steps:

- Go to the "Actions" tab in the repository
- From the "All workflows" page, click on the latest **successful** run from the `dev` branch
- You will see this at the bottom of the page:

![image](https://user-images.githubusercontent.com/10199417/108628548-efdcc100-745b-11eb-8eb9-57a4dfefe63e.png)

- Click on it to download, then extract the `.nupkg` from that `.zip` file into a folder.
- Setup a local NuGet feed in your repository adding that folder as a source
- Add a reference to ComputeSharp v2 in your project from that package source

I will soon be publishing updated docs and wikis on the new version as well.
I know using a local package isn't the most straightforward solution, it's just a temporary thing until I can publish a new preview release on NuGet, but first I want to merge the `d3d12memoryallocator` branch, as that contains some new juicy optimizations 😄

Let me know if that works for you, and thank you for using ComputeSharp! 🥳

**Comment by Iluvatar82** [comment] 2021-02-21 15:33
This is great, thank you!
I managed to get it to work with the Version 1.4.1 but I had to change (kind of) everything:
1. I pulled the whole code into the Execute Function
2. I replaced all Float2's by simple floats for x and y variables because the code generator thought it would be nice to create variable names like "float2" ;)
3. I had to get rid of a simple int[] array = new int[8]{ 0, 0, 0, 1, 1, 0, 1, 1} because in Hlsl arrays are initialized in a different way.

I will definitely try out your preview package! Can it still be run from a .Net Standard 2.1 project?
Your project has been mentioned in a Discord Channel of OpenTK (that's how I "found" your project), do you also plan an interop with OpenGL/OpenCL/OpenTK (like with SharpDX) in the future as well? Sorry for all my questions, I will gladly switch to another medium if one exists!

Thank's very much, Franz!

**Comment by Sergio0694** [comment] 2021-02-21 16:28
Yeah the code generation in v1 isn't the best, especially because it works by decompiling code at runtime, which on its own introduces a lot of weird artifacts that I then need to try to patch up while converting the code to HLSL. Plus I haven't really updated that version of the library in quite a while, so I don't find it hard to believe there's plenty of issues there.
ComputeSharp v2 should be much more reliable, while also being way more feature packed and faster to run 😄

> "I had to get rid of a simple int[] array = new int[8]{ 0, 0, 0, 1, 1, 0, 1, 1} because in Hlsl arrays are initialized in a different way."

That's a nice idea, currently I don't really have support for local arrays, I should definitely add that. Thanks! 🙂

> "Can it still be run from a .Net Standard 2.1 project?"

No, the new version only targets .NET 5, so it's no longer compatible with .NET Standard 2.1 unfortunately.

> "do you also plan an interop with OpenGL/OpenCL/OpenTK (like with SharpDX) in the future as well?"

I don't, ComputeSharp only uses DirectX 12 as a backend. I did however add some interop APIs to allow users to get a raw pointer to the underlying `ID3D12Device` and `ID3D12Resource` objects, in case they wanted to add some more custom features on top. I think it should be possible from there to do some other interop with other backends, assuming there are native APIs available for that (I did hear someone mention a similar thing though, but I'm not familiar with that myself).

> "Sorry for all my questions, I will gladly switch to another medium if one exists!"

No worries, happy to help!
If you have other questions on the lib in general and not strictly related to this issue, feel free to ping me in either the C# Discord server, or the OpenTK server (I just joined there too), just search for my name and you should find my account listed 👍

**Comment by Sergio0694** [comment] 2021-03-07 15:07
Just published a new preview on NuGet from ComputeSharp 2.0, which fixes this issue.
Closing this, feel free to open another one if you want to track the support for declaring local arrays in a shader 🙂

**Closed by Sergio0694** 2021-03-07 15:07 UTC
Labels: bug :bug:, computesharp v1 :hourglass:
