### ISSUE TITLE
Exception in PipelineState constructor

### ISSUE THREAD

**Issue by TinkerWorX** [Sergio0694/ComputeSharp#61] opened 2019-10-03 01:07 UTC
I'm running the included sample project `ComputeSharp.Sample.csproj`

I get the following exception(spaced out for readability) in the PipelineState constructor, when it calls `device.NativeDevice.CreateComputePipelineState(this);`.

```
SharpGen.Runtime.SharpGenException: 
'HRESULT: [0x80070057],
Module: [General],
ApiCode: [E_INVALIDARG/Invalid Arguments],
Message: The parameter is incorrect.'
```

This is the generated shader source
```cpp
/* ===============
 * AUTO GENERATED
 * ===============
 * This shader was created by ComputeSharp.
 * For info or issues: https://github.com/Sergio0694/ComputeSharp */

// Scalar/vector variables
cbuffer _ : register(b0)
{
    uint __x__; // Target X iterations
    uint __y__; // Target Y iterations
    uint __z__; // Target Z iterations
    int width;
}

// ReadWriteBuffer<float> buffer "gpuBuffer"
RWStructuredBuffer<float> gpuBuffer : register(u0);

// Shader body
[Shader("compute")]
[NumThreads(32, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadId)
{
    if (id.x < __x__ &&
        id.y < __y__ &&
        id.z < __z__) // Automatic bounds check
    {
        int i = id.x + id.y * width;
        gpuBuffer[i] *= 2;
    }
}
```

**Notes**: I'm building the project from source myself. The project is also set to target `netcoreapp3.0` instead of `netstandard2.1`.

**Comment by Sergio0694** [comment] 2019-10-03 10:17
Hi, thank you for trying out `ComputeSharp`!
That issue is weird, and it doesn't look like it's actually from my code, but from `SharpGen`, which is used by the DirectX wrapper library I'm using. The HLSL code from that shader looks absolutely fine, so that's not the issue here.
I've had another similar issue reported in the past, and it turned out to be caused by an unsupported GPU device - what GPU are you running this on? Do you have another GPU device to test it on?

**Comment by TinkerWorX** [comment] 2019-10-03 10:23
I have an NVIDIA GeForce GTX 1080 and according to dxdiag my current DirectX version is 12. I've verified that I'm on the latest DirectX I can get through the live update branch.

I might have another GPU device to test on, I'll report back with the results.

I'll also try and include SharpGen as source instead, to see if I can figure out what's failing.

**Comment by Sergio0694** [comment] 2019-10-03 10:26
Huh, that's actually weird, I do have a GTX1080 as well and it works fine for me. I've also tried on a GTX1050 on my notebook and I had no trouble there either. I wonder what's causing this 🤔

**Comment by TinkerWorX** [comment] 2019-10-03 10:51
I just tested with the NuGet package instead of a custom compile and it's the same exception. I'll have time to dig into it later, then I'll return with the results or maybe bounce some things off you.

**Comment by TinkerWorX** [comment] 2019-10-03 21:31
It's not straight forward to build Vortice.Windows from source, so testing isn't easy.

You mentioned `SharpGen`? Do you think it'd be worth bringing up the issue on their tracker instead?

**Comment by Sergio0694** [comment] 2020-08-28 10:09
Hey @TinkerWorX (sorry for the delay!) - would you mind testing this again with the latest release?
It's version `1.4.0` that I published yesterday. I have a GXT1080 on my machine and it works just fine.

Let me know if that solves the issue for you! 😊

**Comment by Sergio0694** [comment] 2020-11-23 01:34
Hey @TinkerWorX - did that new version solve the issue?

If now, would you mind checking out to `feature/terrafx-port` and try the sample from there?
That's a new branch where I completely changed the entire backend using a different library that offers native bindings to all the C++ APIs, so I completely removed the dependency from both `Vortice.Windows` and `SharpGen`. I have a GTX1080 and all samples run fine for me, would be curious if switching to that work in progress branch will work for you too! Let me know 😄

**Comment by Sergio0694** [comment] 2021-03-07 15:09
There is a new preview build of ComputeSharp 2.0 on NuGet that shouldn't have this issue anymore.
Closing this, but feel free to comment or open another issue if you are still experiencing a crash 🙂

**Closed by Sergio0694** 2021-03-07 15:09 UTC
Labels: bug :bug:, computesharp v1 :hourglass:, needs author feedback :memo:
