### ISSUE TITLE
Can't compile shader with double-nested for loop

### ISSUE THREAD

**Issue by rickbrew** [Sergio0694/ComputeSharp#244] opened 2022-04-27 02:37 UTC
The error:
```
D:\src\pdn\src\Windows.Framework\Direct2D1\Effects\RectBoundsEffect.cs(42,37,42,57): error CMPSD2D0034: The shader of type PaintDotNet.Direct2D1.Effects.RectTileBoundsEffect.RectTileBoundsShader failed to compile due to an HLSL compiler error (Message: "The FXC compiler encountered one or more errors while trying to compile the shader: [error X3129]: warning treated as error [error X3570]: gradient instruction used in a loop with varying iteration, attempting to unroll the loop. Make sure to only be using supported features by checking the README file in the ComputeSharp repository: https://github.com/Sergio0694/ComputeSharp. If you're sure that your C# shader code is valid, please open an issue an include a working repro and this error message.")
```

The shader, which is an experiment in taking an input comprised of (x,y,width,height) values and calculating the bounding rectangle for tiled regions within it. For example, if tileSize is (32, 32) then the output would be (inputWidth/32, inputHeight/32) in size, and each output "pixel" would have the `Rect.Union()` of all the "rectangles" stored within a 32x32 region of pixels.

```cs
[D2DInputCount(1)]
[D2DInputComplex(0)]
[D2DRequiresScenePosition]
[D2DEmbeddedBytecode(D2D1ShaderProfile.PixelShader40)]
private readonly partial struct RectTileBoundsShader
    : IPixelShader<RectTileBoundsShader>
{
    static PixelOptions IPixelShader.PixelOptions => PixelOptions.TrivialSampling;
    static int IPixelShader.InputCount => 1;
    static BufferPrecision IPixelShader.BufferPrecision => BufferPrecision.Float32bpc;
    static ChannelDepth IPixelShader.ChannelDepth => ChannelDepth.Four;

    static InputDescription IPixelShader.GetInputDescription(int index)
    {
        switch (index)
        {
            case 0:
                return new InputDescription(Filter.MinMagMipPoint);

            default:
                throw new ArgumentOutOfRangeException();
        }
    }

    static IPixelShaderTransform<RectTileBoundsShader> IPixelShader<RectTileBoundsShader>.CreateTransform(in RectTileBoundsShader shader)
    {
        return new RectTileBoundsTransform(shader);
    }

    public readonly int2 tileSize;

    public float4 Execute()
    {
        float2 scenePos = D2D.GetScenePosition().XY;
        int2 scenePosInt = (int2)Hlsl.Floor(scenePos);
        int2 inputTopLeft = scenePosInt / this.tileSize;
        int2 inputBottomRight = inputTopLeft + this.tileSize;

        float4 boundsLTRB = new Float4(float.PositiveInfinity, float.PositiveInfinity, float.NegativeInfinity, float.NegativeInfinity);
        for (int y = inputTopLeft.Y; y < inputBottomRight.Y; ++y)
        {
            for (int x = inputTopLeft.X; x < inputBottomRight.X; ++x)
            {
                float4 rectXYWH = D2D.SampleInputAtOffset(0, new float2(x, y));
                float4 rectLTRB = new float4(rectXYWH.XY, rectXYWH.XY + rectXYWH.ZW);
                boundsLTRB = new float4(Hlsl.Min(boundsLTRB.XY, rectLTRB.XY), Hlsl.Max(boundsLTRB.ZW, rectLTRB.ZW));
            }
        }

        return new Float4(boundsLTRB.XY, boundsLTRB.ZW - boundsLTRB.XY);
    }
}
```

The error:

**Comment by rickbrew** [comment] 2022-04-27 02:54
Also there's a typo in your error message:

> ... please open an issue _**an**_ include ...

**Comment by Sergio0694** [comment] 2022-04-27 19:33
Closing this as by design as discussed on Discord.
That said I do need to fix that typo, thanks! 😄

**Closed by Sergio0694** 2022-04-27 19:33 UTC
Labels: bug :bug:, untriaged :toolbox:

**Comment by rickbrew** [comment] 2022-04-27 22:41
Okay seems fine to me :) We may start getting additional "bugs" reported / filed for things like this as more folks start wading into CS.D2D1 shaders
