### ISSUE TITLE
BigInteger and BigFloat support

### ISSUE THREAD

**Issue by BinkersSoft** [Sergio0694/ComputeSharp#209] opened 2022-02-07 11:21 UTC
Hello Sergio!

Just started playing with ComputeSharp and already liking it. Using your quick start example I tried using BigInterger and BigFloat types.

https://docs.microsoft.com/en-us/dotnet/api/system.numerics.biginteger?view=net-6.0
https://github.com/FaustVX/BigFloat

I got errors stating they need to be non-nullable. Are you able to guide me on how I can address the errors or is not possible to use these types in ComputeSharp at this time?

![2022-02-07 05_13_23-ConsoleApp1 - Microsoft Visual Studio](https://user-images.githubusercontent.com/25735478/152778508-e42a54d1-b1db-4b34-bb02-056c7f3374a2.png)
![2022-02-07 05_14_02-ConsoleApp1 - Microsoft Visual Studio](https://user-images.githubusercontent.com/25735478/152778509-4d20ef17-59cb-47fd-9fd8-884d0d666571.png)

**Comment by BinkersSoft** [comment] 2022-02-26 21:19
I forgot to mention I understand the issue is with BigInteger and BigFloat potentially being null. My use case will never pass null values. So how can I pass the BigInteger or BigFloat values in a way that ComputeSharp will not complain?

**Comment by xela-trawets** [comment] 2022-02-28 02:18
I hit something like this too, but more basic, I wanted to use bytes...

The types must be types supported by HLSL, and that is sadly not something that can be expressed perfectly in generic constraints, so the error messages may be confusing. (

System.Numerics.BigInteger is not an HLSL thing, so will not make sense for execution, even if the code is otherwise correct. Even many of the primitive types (e.g. byte, short) won't work. 

For a list try this link:
https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-scalar

your milage may vary, I am new here

**Comment by Sergio0694** [comment] 2022-04-23 21:26
Sorry for the delay. The diagnostic is telling you what the issue is: buffers can only support unmanaged types, but `BigFloat` and `BitInteger` are not, as they contain an array internally. [See here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/unmanaged-types) for more info. Closing as by design 🙂

**Closed by Sergio0694** 2022-04-23 21:26 UTC
