### ISSUE TITLE
GraphicsDevice.For not working

### ISSUE THREAD

**Issue by chor64** [Sergio0694/ComputeSharp#105] opened 2021-03-08 17:12 UTC
On the v2.0.0 alpha-1 (nuget), the Gpu.Default.For throws an exeption from the Microsoft.Toolkit.Diagnostics assembly; My theory is that this is probably because Visual Studio couldn't find the correct version (7.0.0 build 776) and instead downloaded 7.0.0-preview5.

**Comment by Sergio0694** [comment] 2021-03-08 17:17
Hey, thanks for the report!

Right, I forgot to update to `7.0.0-Preview5` and accidentally left that package version with is from the preview feed.
Weird that it's crashing though, given that I didn't make any breaking changes in `Microsoft.Toolkit.HighPerformance 7.0.0-Preview5`, so that's interesting. Anyway, I'll update that version and push a new NuGet preview package out, thanks!

**Comment by UlyssesWu** [comment] 2021-03-08 17:22
In fact, v2.0.0 alpha-1 works well on my PC, even with that package version issue.

**Comment by chor64** [comment] 2021-03-08 17:25
Hmm so then it could be a problem with my hardware or something else

**Comment by chor64** [comment] 2021-03-08 17:41
For what i remember it said something like win32 expetion: unspecified exeption. I dont think i passed anything invalid; I just created an empty array, a buffer then tried to run it.
It may also have to do with me using integrated graphics.

**Comment by Sergio0694** [comment] 2021-03-08 17:47
Yeah that just sounds like some COM method failed for some reason, and then the lib used `ThrowHelper` (from the `Diagnostics` package) to actually throw that exception, which is why you saw that coming from the `Microsoft.Toolkit.Diagnostics` assembly.

Essentially you've probably ended up here:

https://github.com/Sergio0694/ComputeSharp/blob/12444bfb48ca427e35428e852235481a67c63391/src/ComputeSharp/Graphics/Extensions/Interop/HResultExtensions.cs#L37-L40

This might be caused by something incorrect being done for your integrated graphics device, yes.
I'll try to see if I can repro this on my notebook, as I have an Intel HD something there 🙂

Just as a test, can you see whether using the WARP device works fine for you instead?

Essentially, just do this:

```csharp
GraphicsDevice gpu = Gpu.QueryDevices(info => !info.IsHardwareAccelerated).First();
```

And then just replace all the occurrences of `Gpu.Default` with this `gpu` instance in your code.

**Comment by chor64** [comment] 2021-03-08 17:56
Ok I'll try to do that when I have some spare time. (Also if this helps; I was using WinForms .Net 5 if that makes any difference)

**Comment by chor64** [comment] 2021-03-08 18:18
Ok so I tested the program with the WARP device and it worked; That means that is probably the integrated graphics' fault.

**Comment by Sergio0694** [comment] 2021-03-08 18:20
Alright, that helps. Definitely still want to investigate this, as even if the integrated GPU didn't support the necessary features to use the library, it should just be automatically skipped when using `Gpu.Default`, you definitely shouldn't be seeing that chrash 😅

**Comment by Sergio0694** [comment] 2021-03-09 15:59
Hey @chor64 - I have investigate this a bit but I'm going to need a proper repro and more info to understand the issue.
Specifically:

1) Can you share the exact minimal repro you're using, and indicate the exact line that's crashing?
2) I would also need the stack trace for the exception, and the exception message and HRESULT
3) Are you using an Insider build of Windows 10? What build are you on?

Additionally, it would help if you could clone the repo and run your repro locally, so that you'd be able to see and share the exact crash right from within ComputeSharp, which would give us more info to investigate the issue.

I'm thinking the crash might be due to your integrated GPU not supporting Shader Model 6.0, which would explain the crash at `Gpu.For` right when the shader is being compiled. I'm looking into a way to test for this in the library, or at the very least add a more useful exception message.

**Comment by chor64** [comment] 2021-03-10 02:43
Sorry for the late reply, i was very busy this day 😅

Alright, just to clarify, I was trying to create an image via the GPU, but then i realized that my integrated graphics didnt support Bgra32, so then i tried with different formats, but it threw an exeption; At first i thought that the exeption was because of the texture buffer/format, but i tried with a linear buffer and didn't work either.

- My version of Windows 10 is 1909 Build 18363.1379

- Here are the exeption details (with some minor edits regarding filenames):

```
  System.ComponentModel.Win32Exception
  HResult=0x80004005
  Message=Unspecified error
  Source=Microsoft.Toolkit.Diagnostics
  StackTrace:
   at Microsoft.Toolkit.Diagnostics.ThrowHelper.ThrowWin32Exception(Int32 error)
   at ComputeSharp.Core.Extensions.HResultExtensions.Assert(Int32 result)
   at ComputeSharp.Shaders.Extensions.ID3D12DeviceExtensions.CreateComputePipelineState(ID3D12Device& d3D12Device, ID3D12RootSignature* d3D12RootSignature, D3D12_SHADER_BYTECODE d3D12ShaderBytecode)
   at ComputeSharp.Shaders.ShaderRunner`1.CreatePipelineData(GraphicsDevice device, CachedShader`1& shaderData, PipelineData& pipelineData)
   at ComputeSharp.Shaders.ShaderRunner`1.Run(GraphicsDevice device, Int32 x, Int32 y, Int32 z, Int32 threadsX, Int32 threadsY, Int32 threadsZ, T& shader)
   at ComputeSharp.Shaders.ShaderRunner`1.Run(GraphicsDevice device, Int32 x, Int32 y, Int32 z, T& shader)
   at ComputeSharp.GraphicsDeviceExtensions.For[T](GraphicsDevice device, Int32 x, T& shader)
   at ProjectName.PathTracer.Run() in PathToProject\Effect.cs:line 19
   at ProjectName.MainForm.RunButton_Click(Object sender, EventArgs e) in PathToProject\MainForm.cs:line 26
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```
For what i understand from the stack trace, its struggling to create the shader.

- I have 2 major classes in my test program; There is a "Effect" script which has the code for running the shader, and the Compute Shader. Here's the Effect class:
```
//cache the device on a static field. Works fine with the WARP device
static readonly GraphicsDevice device = Gpu.Default; //Gpu.QueryDevices(a => !a.IsHardwareAccelerated).First();

//called when a run button is pressed on the main form
public void Run()
{
    float[] data = new float[10];
    using ReadWriteBuffer<float> buffer = device.AllocateReadWriteBuffer(data);
    device.For(buffer.Length, new EffectShader(buffer)); //The program crashes here
    buffer.CopyTo(data);
    Console.WriteLine("First value: " + data[0]);
}
```
- And here the EffectShader class:
```
[AutoConstructor]
public readonly partial struct EffectShader : IComputeShader
{
    public readonly ReadWriteBuffer<float> buffer;

    public void Execute()
    {
        //Just fill the buffer with 1.
        buffer[ThreadIds.X] = 1;
    }
}
```

**Comment by Sergio0694** [comment] 2021-03-10 03:01
Thanks for the additional info!
The delay is absolutely not an issue! We all have busy lives 😄

So, I have two questions:

1) Just to confirm, when you mentioned that the first crash with the image was due to the lack of support for the `Bgra32` format, does that mean that you got a proper exception message saying that instead of just the obscure Win32 error? As in, cases where a given texture format isn't supported should be handled by the library and throw a nice user-friendly exception at least (also see the readme about this, there's methods you can use to check for support at runtime).
2) Ok, so the crash with that sample code sounds like exactly what I was thinking, that your integrated GPU doesn't support Shader Model 6.0, which would explain the crash when creating the pipeline state. I added a fix for that today (https://github.com/Sergio0694/ComputeSharp/commit/a4c0090855c887c48ccfb9d3c2cca9e89b53f20c), so in theory if you grabbed a package from the latest CI run and used it from a local package, if that was indeed the issue, the library should now correctly detect that that feature is missing and just skip the decide, so in your case it would just use the WARP device by default. If you have some time would you mind trying it out to ensure the fix worked for you? 🙂

Alternatively, if that preview package still causes the crash for you, it'd be super useful for me if you could just clone the repo and reference it locally (don't forget to also add the analyzer reference for the source generators, just see the .csproj from the samples), so that we could see exactly what's happening, as then you'd have extra debug info visible in the output window.

But before this, hopefully the preview package will did the trick, if the issue was in fact the lack of SM6 support. Let me know how it goes, and thanks again! 😄

**Comment by chor64** [comment] 2021-03-10 03:09
Yes, the lack of Bgra32 support was handled by the library in a nice way. I did know about the checking supported features methods, in fact, i used it to double check. Very nice support, keep it up!

**Comment by Sergio0694** [comment] 2021-03-10 12:24
Ah, good to know, thanks!
Will leave this issue open until I publish the next alpha package so we can double check that that fixes the crash when using `Gpu.Default` - there's still a few things I'd like to do before uploading that build but should be out soon 😄

**Comment by Sergio0694** [comment] 2021-04-05 10:17
Hi @chor64, I've just published a new preview version, build `2.0.0-alpha.2`.
That includes the fix I mentioned above, could you try checking if that solves the issue for you? Thanks! 😊

**Comment by chor64** [comment] 2021-04-06 16:03
Alright, i updated the package, and it worked. It is now using the Microsoft Basic Render Driver instead of giving an error.

**Comment by Sergio0694** [comment] 2021-04-06 16:04
That's awesome! Thank you for confirming the new version is working for you, really appreciate it! 😊
Will close this then, but do feel free to open another issue if anything else pops up!

**Closed by Sergio0694** 2021-04-06 16:04 UTC
Labels: bug :bug:, needs author feedback :memo:
